const QuoteBase = () => {
    const quotes = [
'ya olduğun gibi görün ya da göründüğün gibi ol',
'Many people limit themselves to leading boring, dull lives by accepting the judgment of others that they are of low intelligence',
'Sabit maaş, yatırım yapamayacak bir gelir ve sen bakmazken artmayan bir hesap yoksa işin içinde sadece kuyruğunu yakalamaya çalışan bir kedisin bunu unutma',
'dil bir hapishanedir - Dil zihnimizin sınırlarını belirler, neyi düşünebileceğinize dağarcığınızdaki kelimeler karar verir,  "dünyamızın sınırlarını dilimizin sınırları belirler" - Ludwig Wittgenstein',
'with self awareness we can respond but without self awareness we just react',
'yalnızlık, insanın çevresinde insan olmaması demek değildir. insan kendisinin önemsediği şeyleri başkalarına ulaştıramadığı ya da başkalarının olanaksız bulduğu görüşlere sahip olduğu zaman kendini yalnız hisseder..." carl gustov jung',
'One of the things you see happening with really successful people is they actually dont get happier as they climb the social ladder, because the people they compare themselves to change',
'dont label people with diffiuclt for example Alper in datafoce ask why questions to him',
'bu videodaki neden motive olamıyorsun bazı şeyler içini anlatıyor, dopamin eksikliği olursa vücudundan istek ve arzu duymuyorsun, bu yüzden çalışmaya bailamıyorusn mesela bu yüzden dopamin detoxu öneriyorlar, mesela bu yüzden sigara içiyorum mesela işte,',
'bilgem cakir irade gücünü kastan olduğundan bahsediyor ve kası ne kadar güçlendirisen o kadar iradeli oluyorsun arada izle motive olmadığın zaman',
'Every time you practice a technique incorrectly, you are increasing your chances of doing it wrong again. Its easy to become very experienced at repeating the same mistakes. Practice doesnt make perfect; only perfect practice makes perfect',
'Learning new things is like building a house. You start with the foundation and build up. If the foundation is faulty the whole thing will crumble down sooner or later.',
'life begins at the end of your comfort zone',
'Amaci olmayan gemiye hiç bir ruzgar yardim etmez',
'Kim oldugunu bulmaya calisma onu yaratmaya calis',
'The biggest obstacle to any transformation is literally just the way we’ve always done things',
'Passions aren’t “found,” they argue. They’re developed',
'Evren kendi kaosunun icinde denge bulmaya calisiyor. Insanlik ufacik evren tarihinde kendine gore uzun sayilacak zamanlarinda kaosun icinde duzen bulma cabasinda',
'Yaşamak bir kültürdür yaşam zevki - özenler ve incelikler kişide olmalı',
'Hayat nasıl bir düzen kurmak istiyorsan öyle şekilleniyor',
'Hayatın anlamı ne? Öğrenmek.',
'Aptallığın en açık kanıtı; Aynı şeyi defalarca yapıp, değişik sonuç almayı beklemektir. Shakespeare',
'Yığınlar içinde herhangi biri olmak istemeyen adam, kendine karşı rahat davranmayı bıraksın.Kişi, amacı için başkalarına özellikle de kendine sert davranmalıdır. NİETZSCHE',
'Sisteme uyuyorsanız fark edilmezsiniz. Sıradan insanlar fark yaratamaz, farkı farklı insanlar yaratır',
'Yaşam ya cesur bir tecrübedir ya da hiçbir şey değildir.',
'Nasıl hayatta kalınacağını biliyor musun? İnsanların sana ihtiyaç duymasını sağlarsın. Hayatta kalırsın çünkü senin elindekine ihtiyaç duymalarını sağlarsın. Ondan sonra başka hiç bir yere gidemezler. Şu an biz ölüyüz. Kimsenin bize ihtiyacı yok. O zaman bize ihtiyaç duymalarını sağlayalım.',
'Aşk, yüzü sevmektir." (Michel Tournier) Beden arzulanır ama sevilen yüzdür',
'Iş olup bitene kadar kimselere bir şey söyleme. Bunu herkes bilir. Ama sen iş olup bittikten sonra da övünme. Bırak başarılarını başkalarından duysunlar daha tesirli olur,',
'Sıra dışı şeylere şaşırmayı öğrenemedim bir türlü! Ben hep "varoluş" umuzu hiç sorgulamadan şu sıradan hayatlarımızı bir ödev gibi sürdürüşümüze şaşırıyorum.',
'Sen düşünceden ibaretsin. Geriye kalan et ve kemiksin. Gül düşünür, gülistan olursun. Diken düşünür, dikenlik olursun',
'Tasavvuf ahlâktan ibarettir. Bu bakımdan ahlâkı senden yüksek olan, senden daha fazla arınmış demektir. (Ebû Bekr el-Kettânî)',
'Nihai olarak zafer ölümün olacaktır. Çünkü doğumla birlikte ölüm zaten bizim kaderimiz olmuştur ve avını yutmadan önce onunla yalnızca kısa bir süre için oynar. Bununla birlikte hayatımıza olabildiğince uzun bir süre için büyük bir ilgi ve özenle devam ederiz. Tıpkı bir sabun köpüğünü sonunda patlayacağından emin olsak da olabildiğince uzun ve büyük şişirmemiz gibi.',
'Inanc ayar podcast ikinci bolumunde bahsettigi konu icsel odak ve dissal odak gercekten cok etkileyici cozum arayan tarafmisin yoksa problemleri baskasina yikan taraf misin? bu bolumu tekrar mutlaka dinle ozellikle cevabini bulamadigin durumlarda',
'Inanc ayar podcast 12. bolum 19.dk da bahsettigi depresyon tanimi cok iyi. depresyon o zamana kadarki benlik projesinin iflasii demek. demek ki yeniden bazi seyler projelenecek ve bu bir isaret',
'konusmalara her zaman kitleye hitap eden sorularla basla, kitlenin problemlerinden basla ya da bir fact vererek ilgilerini cek - konusmada insanlardan ve hikayelerden ornek ver, bir urunden bahsediyorsan direk urundne bahsetme onu yapan insanlar zihniyetlerden bahset, sana guven duymalari lazim once ki seni dinlemek istesinler',
'Inanc Ayar 23.bolumunde 0-3 yas arasi cocuk gelisimini anlatiyor, ileride tekrar dinle',
'Inancin burada bahsettigi bir konu var: gorunur hale gelmek. Calismak ve gorunur halde olmak',
'bilgem cakir bu videoda tam bu noktada motivasyon, rekabetci olma, spor yapma, iddaali olma, basariya aclik konularini guzel ozetliyor. buradan kendime cikaracagim ders basariya acligimi bir rekabet yaratarak bir kurum ya da kisiyle tekrar icimdeki o sonuk atesi yakabilirim, son zamanlarda dusundugum sey bir seyi yapacaksam elimden geken en iyisini yapmam ve en iyi olma vizyonu ile hareket edip ilerlemek oldugunu gordum, hirs sureklilik icin mutlak gereklilik ve sureklilik seni digerlerinden ayirip piramidin ustunde yukseltiyor',
'Selman kahya linkteki videonun ilgili suresinde bahsettigi "ciraklik, ustalik" konulari cok ilham verici. Ozellikle bir seyler uretme konusunda verdigi destekleyici bilgilerde benim de kendime not alabilecegim pek cok nokta var. (ana baslik = paylasim, uretim, ogretmek)',
'Bilgem çakır videosunda bahsettiği iyi yönetici ve kötü yönetici arasındaki fark konusunda çok haklı. Burada diyorki kısaca yöneticilik becerileri aynı zamanda insanları iyi analiz ederek onların nelere yetenekli olduğunu görüp kariyerlerini geliştirici fırsatlar sunarak onlara imkanlar açabilmekte olduğundan bahsediyor.',
'Bilgem çakır derinleşme ve yarım bırakmama, öğrenme alanlarında çok değerli bilgilerden bahsediyor.',
'Teknede yaşayan çizerin videosunda söylediği bir söz beni gerçekten etkiledi. Minimalist yaşamayı seviyorum diyor, yoksunluk hissini seviyorum diyor çünkü her şey dört dörtlük olduğunda ben olmuyorum diyor, bu salaşlık ve bu ortam beni tetikliyor diyor ( burada beni etkileyen benimde böyle bir yaşantıdan gelmiş olmam, ancak şu anda etrafımdaki tüm imkanlardan yararlanıp işime odaklanmam gerekiyor)',
    ],
}

export default QuoteBase